In [81]:
import pandas as pd
import numpy as np
import itertools

import sys, os
from pathlib import Path
source_location = Path().resolve()
sys.path.append(source_location)
from scripts.utils import get_sabdab_details

In [2]:
df_sabdab_all = pd.read_csv(Path.joinpath(source_location,
    'structures/sabdab_summary_all.tsv'), sep="\t")
df_sabdab_90 = pd.read_csv(Path.joinpath(source_location,
    'structures/sabdab_summary_90.tsv'), sep="\t")

df_buried = pd.read_pickle(Path.joinpath(source_location,
    'data/epitope_buried.pickle'))

df_interactions = pd.read_pickle(Path.joinpath(source_location,
    'data/interactions.pickle'))

In [3]:
# protein_antigens = df_sabdab_all[df_sabdab_all['antigen_type'].str.contains("protein", na = False)
protein_antigens = df_sabdab_all.query("antigen_type == antigen_type and antigen_type.str.contains('protein')", engine = 'python').drop_duplicates()
ab_protein_antigens = set(protein_antigens.pdb.values)
all_saddab_proteins = set(df_sabdab_all.pdb.values)
print(
    f"SabDab protein antigen:\n"
    f"{len(ab_protein_antigens)} proteins out of {len(all_saddab_proteins)}, "
    f"{round(len(ab_protein_antigens) / len(all_saddab_proteins) * 100, 1)}%"
)

SabDab protein antigen:
2715 proteins out of 4979, 54.5%


In [4]:
ab_both_chains = set(protein_antigens.query("Hchain == Hchain and Lchain == Lchain").pdb.values)
ab_single_H_chain = set(protein_antigens.query("Hchain == Hchain").pdb.values)
ab_single_L_chain = set(protein_antigens.query("Lchain == Lchain").pdb.values)

n_ab_no_Hchain = len(ab_protein_antigens) - len(ab_single_H_chain)
n_ab_no_Lchain = len(ab_protein_antigens) - len(ab_single_L_chain)

print(f"All: {len(ab_protein_antigens)}\nNo Hchain: {n_ab_no_Hchain}\nNo Lchain: {n_ab_no_Lchain}\nBoth chains: {len(ab_both_chains)}")

All: 2715
No Hchain: 10
No Lchain: 528
Both chains: 2177


In [5]:
buried_fullab = df_buried[df_buried.idcode.isin(ab_both_chains)]
print(
    f"Buried surfaces of {len(set(df_buried.idcode.values))} proteins\n"
    f"with both chains: {len(set(buried_fullab.idcode.values))}"
)

Buried surfaces of 2492 proteins
with both chains: 1974


In [6]:
buried_ab_ag_interface_res = buried_fullab[~buried_fullab[['idcode', 'ab_ag_interface']].astype(str).duplicated(keep='first')][['idcode', 'chainID', 'chain_type', 'ab_ag_interface_res', 'ag_ab_interface_res', 'cdr_seq']]
buried_ab_ag_interface_res = buried_ab_ag_interface_res[~buried_ab_ag_interface_res[['idcode', 'cdr_seq']].astype(str).duplicated(keep='first')][['idcode', 'chainID', 'chain_type', 'ab_ag_interface_res', 'ag_ab_interface_res']]
len(buried_ab_ag_interface_res)

2148

In [7]:
# protein_antigens = df_sabdab_90[df_sabdab_90['antigen_type'].str.contains('protein', na = False)]
protein_antigens = df_sabdab_90.query("antigen_type == antigen_type and antigen_type.str.contains('protein')", engine = 'python').drop_duplicates()
ab_protein_antigens = set(protein_antigens.pdb.values)
all_saddab_proteins = set(df_sabdab_90.pdb.values)
print(
    f"SabDab protein antigen:\n"
    f"{len(ab_protein_antigens)} proteins out of {len(all_saddab_proteins)}, "
    f"{round(len(ab_protein_antigens) / len(all_saddab_proteins) * 100, 1)}%"
)

SabDab protein antigen:
1154 proteins out of 2017, 57.2%


In [8]:
ab_both_chains = set(protein_antigens.query("Hchain == Hchain and Lchain == Lchain").pdb.values)
ab_single_H_chain = set(protein_antigens.query("Hchain == Hchain").pdb.values)
ab_single_L_chain = set(protein_antigens.query("Lchain == Lchain").pdb.values)

n_ab_no_Hchain = len(ab_protein_antigens) - len(ab_single_H_chain)
n_ab_no_Lchain = len(ab_protein_antigens) - len(ab_single_L_chain)

print(f"All: {len(ab_protein_antigens)}\nNo Hchain: {n_ab_no_Hchain}\nNo Lchain: {n_ab_no_Lchain}\nBoth chains: {len(ab_both_chains)}")

All: 1154
No Hchain: 0
No Lchain: 0
Both chains: 1154


In [9]:
buried_fullab = df_buried[df_buried.idcode.isin(ab_both_chains)]
print(
    f"Buried surfaces of {len(set(df_buried.idcode.values))} proteins\n"
    f"with both chains: {len(set(buried_fullab.idcode.values))}"
)

Buried surfaces of 2492 proteins
with both chains: 867


In [10]:
buried_ab_ag_interface_res = buried_fullab[~buried_fullab[['idcode', 'ab_ag_interface']].astype(str).duplicated(keep='first')][['idcode', 'chainID', 'chain_type', 'ab_ag_interface_res', 'ag_ab_interface_res', 'cdr_seq']]
buried_ab_ag_interface_res = buried_ab_ag_interface_res[~buried_ab_ag_interface_res[['idcode', 'cdr_seq']].astype(str).duplicated(keep='first')][['idcode', 'chainID', 'chain_type', 'ab_ag_interface_res', 'ag_ab_interface_res']]
len(buried_ab_ag_interface_res)

947

In [13]:
def count_chains(x):
    ab_chains = protein_antigens.query(f"pdb == '{x['idcode']}' and {'L' if x['chain_type'] in 'LK' else 'H'}chain == '{x['chainID']}'")[['Hchain', 'Lchain']].values
    if len(ab_chains) != 1:
        return (None, None, None, None, None, None, None, None, None, None, None)
    assert len(ab_chains) == 1, print(x['idcode'], x['chain_type'], x['chainID'], ab_chains)
    ab_chains = list(ab_chains[0])

    cdrs = []
    incomplete = False
    for ab_chain in ab_chains:
        if ab_chain != ab_chain:
            cdrs.append((None, None))
            incomplete = True
            continue
        for cdrnumb in (1, 2, 3):
            cdr_info = buried_fullab.query(f"idcode == '{x['idcode']}' and chainID == '{ab_chain}' and cdr == {cdrnumb}")[['cdr_begin', 'cdr_end']].values
            if len(cdr_info) == 1:
                (cdr_b, cdr_e) = cdr_info[0]
                cdrs.append((cdr_b, cdr_e))
            else:
                cdrs.append((None, None))
                incomplete = True

    ag_res = []
    for (chain, resnumb, resname, aname, cdrnumb) in x['ag_ab_interface_res']:
        if aname.startswith('H'):
            continue

        ag_res.append(resname)
    
    ab_res = []
    chains_res = [set(), set()]
    cdrnumbs_res = [set(), set(),  set(), set(), set(), set()]
    for (chain, resnumb, resname, aname, cdrnumb) in x['ab_ag_interface_res']:
        if aname.startswith('H'):
            continue

        ab_res.append(resname)

        if chain == ab_chains[0]:
            i_chain = 0
        elif chain == ab_chains[1]:
            i_chain = 1
        else:
            raise Exception
        
        chains_res[i_chain].add((resnumb))
        for i_cdr in range(i_chain * 3, i_chain * 3 + 3):
            b, e = cdrs[i_cdr]
            if not b:
                continue
            if resnumb >= b and resnumb <= e:
                cdrnumbs_res[i_cdr].add((resnumb))
    
    chains = [len(i) for i in chains_res]
    cdrnumbs = [len(i) for i in cdrnumbs_res]
    
    return (*chains, *cdrnumbs, ab_res, ag_res, incomplete)

buried_ab_ag_interface_res['chains'] =\
    buried_ab_ag_interface_res.apply(lambda x: count_chains(x), axis=1)

In [14]:
buried_ab_ag_interface_res['hchains'], buried_ab_ag_interface_res['lchains'],\
    buried_ab_ag_interface_res['hcdr1'], buried_ab_ag_interface_res['hcdr2'],\
    buried_ab_ag_interface_res['hcdr3'], buried_ab_ag_interface_res['lcdr1'],\
    buried_ab_ag_interface_res['lcdr2'], buried_ab_ag_interface_res['lcdr3'],\
    buried_ab_ag_interface_res['ab_res'], buried_ab_ag_interface_res['ag_res'],\
    buried_ab_ag_interface_res['incomplete'] = zip(*buried_ab_ag_interface_res.chains)

# lost due to incompatibility between Full SabDab and Redudant nomenclature 
len(buried_ab_ag_interface_res.query('hchains == hchains')) 

946

In [15]:
buried_ab_ag_interface_res = buried_ab_ag_interface_res.query('incomplete == 0')

In [16]:
n_interfaces = len(buried_ab_ag_interface_res.query('incomplete == 0'))
n_interfaces_bothchains = len(buried_ab_ag_interface_res.query('hchains != 0 and lchains != 0 and incomplete == 0'))
n_interfaces_hchainonly = len(buried_ab_ag_interface_res.query('hchains != 0 and incomplete == 0')) - n_interfaces_bothchains
n_interfaces_lchainonly = len(buried_ab_ag_interface_res.query('lchains != 0 and incomplete == 0')) - n_interfaces_bothchains
print(
    f"Total interfaces: {n_interfaces}\n",
    f"H+L chains present: {n_interfaces_bothchains} {round(n_interfaces_bothchains / n_interfaces * 100, 1)}\n",
    f"Only H chain present: {n_interfaces_hchainonly} {round(n_interfaces_hchainonly / n_interfaces * 100, 1)}\n",
    f"Only L chain present: {n_interfaces_lchainonly} {round(n_interfaces_lchainonly / n_interfaces * 100, 1)}",
)

import plotly.graph_objects as go

labels = ['H+L chains','Only H chain','Only L']
values = [n_interfaces_bothchains, n_interfaces_hchainonly, n_interfaces_lchainonly]

fig = go.Figure(data=[go.Pie(labels=labels, values=values)])
fig.show()

Total interfaces: 946
 H+L chains present: 897 94.8
 Only H chain present: 47 5.0
 Only L chain present: 2 0.2


In [17]:
heavy_hist = np.histogram(buried_ab_ag_interface_res['hchains'], range=(0, 20), bins=10, density=True)
light_hist = np.histogram(buried_ab_ag_interface_res['lchains'], range=(0, 20), bins=10, density=True)
heavy_mean, light_mean = buried_ab_ag_interface_res['hchains'].mean(), buried_ab_ag_interface_res['lchains'].mean()

print(f'Number of Residues\nAvg Heavy chain: {round(heavy_mean, 1)}\nAvg Light chain: {round(light_mean, 1)}')
print(heavy_hist)
print(light_hist)

fig = go.Figure()
fig.add_trace(go.Scatter(y=heavy_hist[0], x=heavy_hist[1],
                    mode='lines+markers', line_shape='spline',
                    name='Heavy Chain'))
fig.add_trace(go.Scatter(y=light_hist[0], x=light_hist[1],
                    mode='lines+markers', line_shape='spline',
                    name='Light Chain'))
fig.update_layout(
    xaxis_title="# Residues",
    yaxis_title="Probability Density",
    template="plotly_white",
    autosize=False,
    width=500,
    height=500,
    margin=dict(
        l=50,
        r=50,
        b=100,
        t=100,
        pad=4
    ),
)
fig.show()

Number of Residues
Avg Heavy chain: 9.7
Avg Light chain: 5.1
(array([0.01804671, 0.014862  , 0.03821656, 0.06794055, 0.09766454,
       0.10721868, 0.07165605, 0.05467091, 0.01963907, 0.01008493]), array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]))
(array([0.05720339, 0.10222458, 0.13930085, 0.10752119, 0.05773305,
       0.02330508, 0.00635593, 0.00317797, 0.00264831, 0.00052966]), array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]))


In [18]:

tot_hcdr1, tot_hcdr2, tot_hcdr3 = buried_ab_ag_interface_res['hcdr1'].sum(), buried_ab_ag_interface_res['hcdr2'].sum(), buried_ab_ag_interface_res['hcdr3'].sum()
tot_hchain_cdr = tot_hcdr1 + tot_hcdr2 + tot_hcdr3
tot_lcdr1, tot_lcdr2, tot_lcdr3 = buried_ab_ag_interface_res['lcdr1'].sum(), buried_ab_ag_interface_res['lcdr2'].sum(), buried_ab_ag_interface_res['lcdr3'].sum()
tot_lchain_cdr = tot_lcdr1 + tot_lcdr2 + tot_lcdr3
tot_all = tot_hchain_cdr + tot_lchain_cdr
print(
    '        TOTAL\n'
    f'HEAVY: {int(tot_hchain_cdr)} ({round(tot_hchain_cdr / tot_all * 100, 1)}%)  \n'
    f'LIGHT: {int(tot_lchain_cdr)} ({round(tot_lchain_cdr / tot_all * 100, 1)}%)  \n'
)
print(
    f'       CDR1    CDR2    CDR3\n'
    'HEAVY: '
    f'{int(tot_hcdr1)} ({round(tot_hcdr1 / tot_all * 100, 1)}%) '
    f'{int(tot_hcdr2)} ({round(tot_hcdr2 / tot_all * 100, 1)}%) '
    f'{int(tot_hcdr3)} ({round(tot_hcdr3 / tot_all * 100, 1)}%)\n'
    f'LIGHT: {int(tot_lcdr1)} ({round(tot_lcdr1 / tot_all * 100, 1)}%) '
    f' {int(tot_lcdr2)}  ({round(tot_lcdr2 / tot_all * 100, 1)}%) '
    f'{int(tot_lcdr3)} ({round(tot_lcdr3 / tot_all * 100, 1)}%)\n'
    'TOTAL: '
    f'{int(tot_hcdr1 + tot_lcdr1)} ({round((tot_hcdr1 + tot_lcdr1) / tot_all * 100, 1)}%) '
    f'{int(tot_hcdr2 + tot_lcdr2)} ({round((tot_hcdr2 + tot_lcdr2) / tot_all * 100, 1)}%) '
    f'{int(tot_hcdr3 + tot_lcdr3)} ({round((tot_hcdr3 + tot_lcdr3) / tot_all * 100, 1)}%)\n'
)

        TOTAL
HEAVY: 7144 (62.6%)  
LIGHT: 4261 (37.4%)  

       CDR1    CDR2    CDR3
HEAVY: 1446 (12.7%) 2009 (17.6%) 3689 (32.3%)
LIGHT: 1608 (14.1%)  707  (6.2%) 1946 (17.1%)
TOTAL: 3054 (26.8%) 2716 (23.8%) 5635 (49.4%)



In [19]:
hrange = (0, 10)
hcdr1_hist = np.histogram(buried_ab_ag_interface_res['hcdr1'], range=hrange, bins=10)
hcdr2_hist = np.histogram(buried_ab_ag_interface_res['hcdr2'], range=hrange, bins=10)
hcdr3_hist = np.histogram(buried_ab_ag_interface_res['hcdr3'], range=hrange, bins=10)
lcdr1_hist = np.histogram(buried_ab_ag_interface_res['lcdr1'], range=hrange, bins=10)
lcdr2_hist = np.histogram(buried_ab_ag_interface_res['lcdr2'], range=hrange, bins=10)
lcdr3_hist = np.histogram(buried_ab_ag_interface_res['lcdr3'], range=hrange, bins=10)

print('Average CDR length (number of residues)')
print(
    '   CDR1 CDR2 CDR3\n'
    f'H : {round(buried_ab_ag_interface_res["hcdr1"].mean(), 1)} '
    f' {round(buried_ab_ag_interface_res["hcdr2"].mean(), 1)} '
    f' {round(buried_ab_ag_interface_res["hcdr3"].mean(), 1)}\n'
    f'L : {round(buried_ab_ag_interface_res["lcdr1"].mean(), 1)} '
    f' {round(buried_ab_ag_interface_res["lcdr2"].mean(), 1)} '
    f' {round(buried_ab_ag_interface_res["lcdr3"].mean(), 1)}'
)
print(hcdr1_hist)
print(hcdr2_hist)
print(hcdr3_hist)
print(lcdr1_hist)
print(lcdr2_hist)
print(lcdr3_hist)

fig = go.Figure()
fig.add_trace(go.Scatter(y=hcdr1_hist[0][1:], x=hcdr1_hist[1][1:],
                    mode='lines+markers', line_shape='spline',
                    name='H CDR 1'))
fig.add_trace(go.Scatter(y=hcdr2_hist[0][1:], x=hcdr2_hist[1][1:],
                    mode='lines+markers', line_shape='spline',
                    name='H CDR 2'))
fig.add_trace(go.Scatter(y=hcdr3_hist[0][1:], x=hcdr3_hist[1][1:],
                    mode='lines+markers', line_shape='spline',
                    name='H CDR 3'))
fig.add_trace(go.Scatter(y=lcdr1_hist[0][1:], x=lcdr1_hist[1][1:],
                    mode='lines+markers', line_shape='spline',
                    name='L CDR 1'))
fig.add_trace(go.Scatter(y=lcdr2_hist[0][1:], x=lcdr2_hist[1][1:],
                    mode='lines+markers', line_shape='spline',
                    name='L CDR 2'))
fig.add_trace(go.Scatter(y=lcdr3_hist[0][1:], x=lcdr3_hist[1][1:],
                    mode='lines+markers', line_shape='spline',
                    name='L CDR 3'))
fig.update_layout(
    xaxis_title="# Residues",
    yaxis_title="Probability Density",
    template="plotly_white",
    autosize=False,
    width=500,
    height=500,
    margin=dict(
        l=50,
        r=50,
        b=100,
        t=100,
        pad=4
    ),
    xaxis_range=(0.5, 9.5),
    xaxis = dict(
        tickmode = 'linear',
        tick0 = 1,
        dtick = 1
    )
)
fig.show()

Average CDR length (number of residues)
   CDR1 CDR2 CDR3
H : 1.5  2.1  3.9
L : 1.7  0.7  2.1
(array([341, 162, 206, 131,  63,  33,   8,   2,   0,   0]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))
(array([179, 160, 202, 214, 156,  31,   4,   0,   0,   0]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))
(array([ 23,  91, 109, 198, 214, 134,  81,  43,  28,  19]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))
(array([272, 212, 191, 151,  67,  30,  19,   3,   1,   0]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))
(array([557, 218,  88,  47,  17,  13,   3,   3,   0,   0]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))
(array([237, 146, 182, 176, 138,  53,  11,   1,   0,   2]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))


In [20]:
only_framework = len(buried_ab_ag_interface_res.query('(hcdr1 + hcdr2 + hcdr3 + lcdr1 + lcdr2 + lcdr3) == 0'))
only_cdr = len(buried_ab_ag_interface_res.query('(hcdr1 + hcdr2 + hcdr3 + lcdr1 + lcdr2 + lcdr3) == (hchains + lchains)'))

print(
    f'Only FRAMEWORK: {round(only_framework / len(buried_ab_ag_interface_res) * 100, 1)}%\n'
    f'Only CDR: {round(only_cdr / len(buried_ab_ag_interface_res) * 100, 1)}%\n'
    f'CDR + Framework: {round((len(buried_ab_ag_interface_res) - (only_framework + only_cdr)) / len(buried_ab_ag_interface_res) * 100, 1)}%'
)

Only FRAMEWORK: 0.2%
Only CDR: 14.0%
CDR + Framework: 85.8%


In [21]:
def get_cdr_perc(x):
    hcdr = x['hcdr1'] + x['hcdr2'] + x['hcdr3']
    lcdr = x['lcdr1'] + x['lcdr2'] + x['lcdr3']
    cdr = hcdr + lcdr
    total = x['hchains'] + x['lchains']
    return cdr / total

cdr_perc = buried_ab_ag_interface_res.apply(lambda x: get_cdr_perc(x), axis=1)
cdr_hist = np.histogram(cdr_perc, bins=10, density=True)

print(f'Avg CDR interaction: {round(cdr_perc.mean() * 100, 1)}%')
print(cdr_hist)


fig = go.Figure()
fig.add_trace(go.Scatter(y=cdr_hist[0], x=cdr_hist[1]*100,
                    mode='lines+markers', line_shape='spline',
                    name='Heavy Chain'))
fig.update_layout(
    xaxis_title="CDR Interactions (%)",
    yaxis_title="Probability Density",
    template="plotly_white",
    autosize=False,
    width=500,
    height=500,
    margin=dict(
        l=50,
        r=50,
        b=100,
        t=100,
        pad=4
    ),
    xaxis_range=[0,101]
)
fig.show()

Avg CDR interaction: 82.8%
(array([0.02114165, 0.        , 0.01057082, 0.0845666 , 0.26427061,
       0.28541226, 0.6448203 , 1.80761099, 3.75264271, 3.12896406]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))


In [22]:
tot_hchain_all = buried_ab_ag_interface_res['hchains'].sum()
tot_lchain_all = buried_ab_ag_interface_res['lchains'].sum()
print(
    "          All    CDR  Framework\n "
    f"HEAVY:  {int(tot_hchain_all)}   {int(tot_hchain_cdr)}  {int(tot_hchain_all - tot_hchain_cdr)}\n",
    f"LIGHT:  {int(tot_lchain_all)}   {int(tot_lchain_cdr)}   {int(tot_lchain_all - tot_lchain_cdr)}\n",
    f"TOTAL: {int(tot_hchain_all + tot_lchain_all)}  {int(tot_hchain_cdr + tot_lchain_cdr)}  {int((tot_hchain_all - tot_hchain_cdr) + (tot_lchain_all - tot_lchain_cdr))}"
)


          All    CDR  Framework
 HEAVY:  9189   7144  2045
 LIGHT:  4820   4261   559
 TOTAL: 14009  11405  2604


In [23]:
def count_cdrs(x):
    n_cdrs = 0
    for cdr_i in x[['hcdr1', 'hcdr2', 'hcdr3', 'lcdr1', 'lcdr2', 'lcdr3']]:
        if cdr_i > 0:
            n_cdrs += 1
    return n_cdrs


buried_ab_ag_interface_res['n_cdrs'] = buried_ab_ag_interface_res.apply(lambda x: count_cdrs(x), axis=1)

n_cdrs_hist = np.histogram(buried_ab_ag_interface_res['n_cdrs'], range=(0.5,6.5), bins=6, density=True)
print(f"Avg number of CDRs: {round(buried_ab_ag_interface_res['n_cdrs'].mean(), 1)}")
print(n_cdrs_hist)

fig = go.Figure()
fig.add_trace(go.Scatter(y=n_cdrs_hist[0], x=n_cdrs_hist[1],
                    mode='lines+markers', line_shape='spline',
                    name='Heavy Chain'))
fig.update_layout(
    xaxis_title="Number of Interacting CDR Chains",
    yaxis_title="Probability Density",
    template="plotly_white",
    autosize=False,
    width=500,
    height=500,
    margin=dict(
        l=50,
        r=50,
        b=100,
        t=100,
        pad=4
    )
)
fig.show()


Avg number of CDRs: 4.3
(array([0.00211864, 0.04555085, 0.1875    , 0.31038136, 0.31567797,
       0.13877119]), array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]))


In [24]:
def get_cdr3_len(x):
    ab_chains = protein_antigens.query(
        f"pdb == '{x['idcode']}' and {'L' if x['chain_type'] in 'LK' else 'H'}chain == '{x['chainID']}'", engine = 'python')[['Hchain', 'Lchain']].values
    assert len(ab_chains) == 1, print(ab_chains)
    ab_chains = list(ab_chains[0])
    
    cdr3 = buried_fullab.query(
        f'idcode == "{x["idcode"]}" and chainID.isin({ab_chains}) and cdr == 3', engine = 'python')['cdr_seq'].values[0]
    return len(cdr3)


buried_ab_ag_interface_res['cdr3_len'] = buried_ab_ag_interface_res.apply(lambda x: get_cdr3_len(x), axis=1)

In [25]:
cdr3_hist, cdr3_bins = np.histogram(buried_ab_ag_interface_res['cdr3_len'], bins=10, range=(0, 30), density=True)
print(cdr3_hist, cdr3_bins)
fig = go.Figure()
fig.add_trace(go.Scatter(y=cdr3_hist, x=cdr3_bins,
                    mode='lines+markers', line_shape='spline',
                    name='Heavy Chain'))
fig.update_layout(
    xaxis_title="# of Residues in CDR3",
    yaxis_title="Probability Density",
    template="plotly_white",
    autosize=False,
    width=500,
    height=500,
    margin=dict(
        l=50,
        r=50,
        b=100,
        t=100,
        pad=4
    )
)
fig.show()

[0.         0.00812147 0.03742938 0.09922316 0.08933616 0.05049435
 0.02860169 0.01129944 0.00847458 0.00035311] [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]


In [26]:
bins = [[] for i in cdr3_bins[1:]]
bins_i = list(enumerate(cdr3_bins[1:]))
for n_int_cdrs, cdr3_len in buried_ab_ag_interface_res[['n_cdrs', 'cdr3_len']].values:
    for i, upper_bound in bins_i:
        if cdr3_len <= upper_bound:
            bins[i].append(n_int_cdrs)

In [27]:
avg_n_cdrs_bins = [round(sum(i)/len(i), 2) for i in bins]
print(avg_n_cdrs_bins)

[5.0, 5.25, 4.86, 4.66, 4.52, 4.42, 4.37, 4.31, 4.31, 4.3]


In [28]:
def aa_dist(aa_lists):
    dist = {}
    for aas in aa_lists:
        for aa in aas:
            if aa not in dist:
                dist[aa] = 0
            dist[aa] += 1

    return dist

allaas_dist = aa_dist(buried_ab_ag_interface_res['ab_res'].values)
allaas_dist

{'THR': 1574,
 'SER': 3022,
 'TRP': 3841,
 'ASN': 1922,
 'ARG': 1793,
 'ILE': 697,
 'GLY': 2215,
 'PHE': 2160,
 'LEU': 870,
 'TYR': 10620,
 'GLN': 496,
 'GLU': 818,
 'VAL': 680,
 'ASP': 1763,
 'LYS': 408,
 'MET': 180,
 'PRO': 554,
 'CYS': 78,
 'ALA': 758,
 'HIS': 734}

In [29]:
allaas_dist = aa_dist(buried_ab_ag_interface_res['ag_res'].values)
allaas_dist

{'GLU': 1869,
 'THR': 1923,
 'PHE': 1744,
 'HIS': 976,
 'ARG': 2328,
 'SER': 1691,
 'PRO': 1474,
 'LEU': 1464,
 'GLN': 1555,
 'VAL': 933,
 'MET': 385,
 'CYS': 377,
 'ILE': 952,
 'ALA': 1151,
 'LYS': 1920,
 'ASP': 2017,
 'ASN': 2334,
 'GLY': 2118,
 'TRP': 1173,
 'TYR': 2328}

In [30]:
import sys
sys.path.append('scripts')

from scripts.utils import read_pdb_line
from Bio.Data.IUPACData import protein_letters_3to1 as AA_CONVERTER

def get_sequence(pdb_path, chains):
    prot_aas = []
    last = None
    with open(pdb_path) as f:
        for line in f:
            if line.startswith("ATOM"):
                chain, cdr_id, res, *_ = read_pdb_line(line)
                (resname, resnumb) = res
                new = resname, chain, resnumb, cdr_id
                if chain in chains and last != new:
                    res = AA_CONVERTER[resname.capitalize()]
                    prot_aas.append(resname)
                last = new[:]
    return prot_aas

aas = []
for idcode in buried_ab_ag_interface_res.idcode.unique():
    pdb_path = f"structures/raw/{idcode}.pdb"
    chains = protein_antigens.query(f'pdb == "{idcode}"')['antigen_chain'].unique()
    prot_aas = get_sequence(pdb_path, chains)
    aas.append(prot_aas)

aa_dist(aas)

{'MET': 7413,
 'LEU': 39638,
 'PRO': 22740,
 'ARG': 19670,
 'TRP': 7233,
 'GLU': 23752,
 'ALA': 27632,
 'TYR': 18171,
 'SER': 33797,
 'GLY': 31418,
 'PHE': 21932,
 'HIS': 9456,
 'VAL': 33016,
 'LYS': 25870,
 'ASP': 22109,
 'GLN': 19620,
 'THR': 33282,
 'ILE': 28738,
 'CYS': 14257,
 'ASN': 30231}

In [31]:
def filter_res(residues):
    res = set()
    for chain, resnumb, resname, aname, cdrnumb in residues:
        if aname.startswith('H'):
            continue
        res.add((chain, resnumb, resname))
    return res

def count_interchain(x):
    ab_chains = protein_antigens.query(
        f"pdb == '{x['idcode']}' and {'L' if x['chain_type'] in 'LK' else 'H'}chain == '{x['chainID']}'", engine = 'python')[['Hchain', 'Lchain']].values
    assert len(ab_chains) == 1, print(ab_chains)
    ab_chains = list(ab_chains[0])
    
    
    cdrs = buried_fullab.query(
        f'idcode == "{x["idcode"]}" and chainID.isin({ab_chains})', engine = 'python')
    assert len(cdrs) == 6, print(cdrs)
    cdr1, cdr2, cdr3, cdr4, cdr5, cdr6 = [filter_res(i) for i in cdrs['ag_cdr_interface_res'].values]
    
    shared_cdr = []
    all_cdrs = (cdr1, cdr2, cdr3, cdr4, cdr5, cdr6)
    for (i, j) in itertools.combinations(range(len(all_cdrs)), 2):
        if i == j:
            continue
        cdr_i = all_cdrs[i]
        cdr_j = all_cdrs[j]
        shared_cdrij = len(cdr_i.intersection(cdr_j))
        shared_cdr.append(shared_cdrij)

    ag_cdr_res = filter_res([ii for i in cdrs['ag_cdr_interface_res'].values for ii in i])
    ag_chain_res = filter_res([ii for i in cdrs['ag_cdrchain_interface_res'].values for ii in i])
    ag_res = filter_res([ii for i in cdrs['ag_ab_interface_res'].values for ii in i])
    inter_chain = ag_res - ag_chain_res
    inter_cdr = ag_chain_res - ag_cdr_res
    
    return (len(inter_chain), len(inter_cdr), len(ag_res), *shared_cdr)

buried_ab_ag_interface_res["cdr_info"] = buried_ab_ag_interface_res.apply(lambda x: count_interchain(x), axis=1)
buried_ab_ag_interface_res["inter_chain"], buried_ab_ag_interface_res["inter_cdr"], buried_ab_ag_interface_res["ag_res"], buried_ab_ag_interface_res["cdr_12"], buried_ab_ag_interface_res["cdr_13"], buried_ab_ag_interface_res["cdr_14"], buried_ab_ag_interface_res["cdr_15"], buried_ab_ag_interface_res["cdr_16"], buried_ab_ag_interface_res["cdr_23"], buried_ab_ag_interface_res["cdr_24"], buried_ab_ag_interface_res["cdr_25"], buried_ab_ag_interface_res["cdr_26"], buried_ab_ag_interface_res["cdr_34"], buried_ab_ag_interface_res["cdr_35"], buried_ab_ag_interface_res["cdr_36"], buried_ab_ag_interface_res["cdr_45"], buried_ab_ag_interface_res["cdr_46"], buried_ab_ag_interface_res["cdr_56"] = zip(*buried_ab_ag_interface_res.cdr_info)

In [32]:
print(np.histogram(buried_ab_ag_interface_res['inter_chain'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5]))
print(np.histogram(buried_ab_ag_interface_res['inter_cdr'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 26]))
print(np.histogram(buried_ab_ag_interface_res['ag_res'], range=(0, 40), bins=10))

print(buried_ab_ag_interface_res['ag_res'].mean())
print(buried_ab_ag_interface_res['inter_cdr'].mean() / 6)

(array([774, 154,  16,   2]), array([-0.5,  0.5,  1.5,  2.5,  3.5]))
(array([314, 272, 143,  99,  37,  16,  64]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5,  5.5, 26. ]))
(array([  4,  31, 220, 309, 251,  90,  31,   6,   1,   2]), array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.]))
14.662790697674419
0.3023255813953488


In [33]:
print(np.histogram(buried_ab_ag_interface_res['cdr_12'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_12'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_13'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_13'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_14'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_14'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_15'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_15'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_16'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_16'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_23'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_23'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_24'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_24'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_25'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_25'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_26'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_26'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_34'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_34'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_35'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_35'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_36'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_36'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_45'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_45'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_46'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_46'].mean())
print(np.histogram(buried_ab_ag_interface_res['cdr_45'], bins=[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5]), buried_ab_ag_interface_res['cdr_45'].mean())

print(max(buried_ab_ag_interface_res['cdr_12']), max(buried_ab_ag_interface_res['cdr_13']), max(buried_ab_ag_interface_res['cdr_14']), max(buried_ab_ag_interface_res['cdr_15']), max(buried_ab_ag_interface_res['cdr_16']), max(buried_ab_ag_interface_res['cdr_23']), max(buried_ab_ag_interface_res['cdr_24']), max(buried_ab_ag_interface_res['cdr_25']), max(buried_ab_ag_interface_res['cdr_26']), max(buried_ab_ag_interface_res['cdr_34']), max(buried_ab_ag_interface_res['cdr_35']), max(buried_ab_ag_interface_res['cdr_36']), max(buried_ab_ag_interface_res['cdr_45']), max(buried_ab_ag_interface_res['cdr_46']), max(buried_ab_ag_interface_res['cdr_45']))

(array([768, 156,  21,   1,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.2124735729386892
(array([734, 154,  52,   6,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.2917547568710359
(array([943,   2,   1,   0,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.004228329809725159
(array([941,   5,   0,   0,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.005285412262156448
(array([943,   3,   0,   0,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.003171247357293869
(array([728, 180,  34,   4,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.2748414376321353
(array([943,   3,   0,   0,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.003171247357293869
(array([943,   3,   0,   0,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.003171247357293869
(array([896,  47,   3,   0,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.056025369978858354
(array([663, 229,  52,   2,   0]), array([-0.5,  0.5,  1.5,  2.5,  3.5,  4.5])) 0.358350951374207

In [34]:
z = [
    [None, buried_ab_ag_interface_res['cdr_12'].mean(),buried_ab_ag_interface_res['cdr_13'].mean(),buried_ab_ag_interface_res['cdr_14'].mean(),buried_ab_ag_interface_res['cdr_15'].mean(),buried_ab_ag_interface_res['cdr_16'].mean()],
    [buried_ab_ag_interface_res['cdr_12'].mean(),None,buried_ab_ag_interface_res['cdr_23'].mean(),buried_ab_ag_interface_res['cdr_24'].mean(),buried_ab_ag_interface_res['cdr_25'].mean(),buried_ab_ag_interface_res['cdr_26'].mean()],
    [buried_ab_ag_interface_res['cdr_13'].mean(),buried_ab_ag_interface_res['cdr_23'].mean(),None,buried_ab_ag_interface_res['cdr_34'].mean(),buried_ab_ag_interface_res['cdr_35'].mean(),buried_ab_ag_interface_res['cdr_36'].mean()],
    [buried_ab_ag_interface_res['cdr_14'].mean(),buried_ab_ag_interface_res['cdr_24'].mean(),buried_ab_ag_interface_res['cdr_34'].mean(),None,buried_ab_ag_interface_res['cdr_45'].mean(),buried_ab_ag_interface_res['cdr_46'].mean()],
    [buried_ab_ag_interface_res['cdr_15'].mean(),buried_ab_ag_interface_res['cdr_25'].mean(),buried_ab_ag_interface_res['cdr_35'].mean(),buried_ab_ag_interface_res['cdr_45'].mean(),None,buried_ab_ag_interface_res['cdr_56'].mean()],
    [buried_ab_ag_interface_res['cdr_16'].mean(),buried_ab_ag_interface_res['cdr_26'].mean(),buried_ab_ag_interface_res['cdr_36'].mean(),buried_ab_ag_interface_res['cdr_46'].mean(),buried_ab_ag_interface_res['cdr_56'].mean(),None],
]

fig = go.Figure(data=go.Heatmap(colorscale=('white', 'black'), z=z, x=['H CDR 1', 'H CDR 2', 'H CDR 3', 'L CDR 1', 'L CDR 2', 'L CDR 3'], y=['H CDR 1', 'H CDR 2', 'H CDR 3', 'L CDR 1', 'L CDR 2', 'L CDR 3']))
fig.show()

In [35]:
clean_idcodes = set(buried_ab_ag_interface_res.idcode.values)
hbonds = []
wms = []
for (idcode, ab_h_chain, ab_l_chain, ag_chain, interactions) in df_interactions:
    if idcode not in clean_idcodes:
        continue
    _, _ , _, _, _, _, hhbonds, lhbonds, hwm, lwm = interactions
    i_hbonds = len(hhbonds) + len(lhbonds)
    hbonds.append(i_hbonds)

    i_wms = len(hwm) + len(lwm)
    wms.append(i_wms)

print(np.histogram(hbonds, range=(0, 40), bins=10))
print(sum(hbonds) / len(hbonds), len(hbonds))

print(np.histogram(wms, range=(0, 280), bins=10))
print(sum(wms) / len(wms), len(wms))


(array([ 7, 20, 53, 55, 48, 29, 13,  9,  3,  1]), array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.]))
14.974789915966387 238
(array([ 1,  9, 46, 65, 50, 42, 13,  4,  6,  2]), array([  0.,  28.,  56.,  84., 112., 140., 168., 196., 224., 252., 280.]))
116.8109243697479 238


In [36]:
def count_linear_seqs(x, tolerance):
    ab_chains = protein_antigens.query(
        f"pdb == '{x['idcode']}' and {'L' if x['chain_type'] in 'LK' else 'H'}chain == '{x['chainID']}'")[['Hchain', 'Lchain']].values
    assert len(ab_chains) == 1, print(ab_chains)
    ab_chains = list(ab_chains[0])
    
    cdr_epitope = buried_fullab.query(
        f'idcode == "{x["idcode"]}"')['ag_ab_interface_res'].values[0]
    
    epitope = {}
    for atom in cdr_epitope:
        chain, resnumb, resname, aname, _ = atom
        if aname.startswith('H'):
            continue
        if chain not in epitope:
            epitope[chain] = []
        epitope[chain].append(resnumb)

    seq_lens = []
    for chain, res in epitope.items():
        n_seqs = 0
        prev = None
        ep_seq = 0
        res = sorted(set(res))
        for i, resnumb in enumerate(res):
            if prev and (resnumb != prev + 1 and resnumb > prev + 1 + tolerance):
                seq_lens.append(ep_seq)
                ep_seq = 0
            prev = resnumb
            ep_seq += 1
        seq_lens.append(ep_seq)
    
    return seq_lens

buried_ab_ag_interface_res["epi_seq_len_0"] = buried_ab_ag_interface_res.apply(lambda x: count_linear_seqs(x, 0), axis=1)
buried_ab_ag_interface_res["epi_seq_len_1"] = buried_ab_ag_interface_res.apply(lambda x: count_linear_seqs(x, 1), axis=1)
buried_ab_ag_interface_res["epi_seq_len_3"] = buried_ab_ag_interface_res.apply(lambda x: count_linear_seqs(x, 3), axis=1)


In [37]:
all_epi_seqs, epi_seqs_per_ab = [], []
for epi_seqs in buried_ab_ag_interface_res["epi_seq_len_0"]:
    all_epi_seqs += epi_seqs
    epi_seqs_per_ab.append(len(epi_seqs))

print(np.histogram(all_epi_seqs, bins=10, range=(0, 20)))
print(np.histogram(epi_seqs_per_ab, bins=10, range=(0, 30)))

all_epi_seqs, epi_seqs_per_ab = [], []
for epi_seqs in buried_ab_ag_interface_res["epi_seq_len_1"]:
    all_epi_seqs += epi_seqs
    epi_seqs_per_ab.append(len(epi_seqs))

print(np.histogram(all_epi_seqs, bins=10, range=(0, 20)))
print(np.histogram(epi_seqs_per_ab, bins=10, range=(0, 30)))

all_epi_seqs, epi_seqs_per_ab = [], []
for epi_seqs in buried_ab_ag_interface_res["epi_seq_len_3"]:
    all_epi_seqs += epi_seqs
    epi_seqs_per_ab.append(len(epi_seqs))

print(np.histogram(all_epi_seqs, bins=10, range=(0, 20)))
print(np.histogram(epi_seqs_per_ab, bins=10, range=(0, 30)))


(array([3892, 2160,  630,  204,   86,   13,    1,    0,    0,    0]), array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]))
(array([ 25, 233, 393, 203,  80,   8,   3,   0,   1,   0]), array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]))
(array([1990, 1591,  776,  399,  150,   51,   14,    5,    0,    0]), array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]))
(array([ 68, 511, 276,  83,   6,   2,   0,   0,   0,   0]), array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]))
(array([ 926, 1151,  759,  445,  225,   99,   46,   15,    6,    1]), array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]))
(array([193, 609, 129,  13,   2,   0,   0,   0,   0,   0]), array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]))


In [38]:
def count_atomtypes(x):
    ab_chains = protein_antigens.query(
        f"pdb == '{x['idcode']}' and {'L' if x['chain_type'] in 'LK' else 'H'}chain == '{x['chainID']}'", engine = 'python')[['Hchain', 'Lchain']].values
    assert len(ab_chains) == 1, print(ab_chains)
    ab_chains = list(ab_chains[0])
    
    epitope = buried_fullab.query(
        f'idcode == "{x["idcode"]}" and chainID.isin({ab_chains})', engine = 'python')['ag_ab_interface_res'].values[0]
    
    ag_atom_dist = {}
    
    for atom in epitope:
        chain, resnumb, resname, aname, _ = atom
        if aname.startswith('H'):
            continue
        if aname[0] not in ag_atom_dist:
            ag_atom_dist[aname[0]] = 0
        ag_atom_dist[aname[0]] += 1
    
    return ag_atom_dist

buried_ab_ag_interface_res['atom_hist'] = buried_ab_ag_interface_res.apply(lambda x: count_atomtypes(x), axis=1)

In [39]:
atom_hist = {'N': [], 'C': [], 'O': [], 'S': []}
for atoms in buried_ab_ag_interface_res['atom_hist']:
    for atom, count in atoms.items():
        atom_hist[atom].append(count)

In [40]:
print(np.histogram(atom_hist['C'], range=(0, 50), bins=10))

(array([  5,  30, 117, 230, 271, 169,  84,  28,   7,   4]), array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.]))


----------

In [ ]:
import mdtraj as md
casa_dir = Path("/home/pbarletta/labo/22/AbAgInterface")

In [181]:
buried_fullab.iloc[4805]

idcode                                                                    4ydk
chainID                                                                      H
chain_type                                                                   H
cdr                                                                          3
cdr_seq                                                   VTFYHEGSGYYYRAGNYFDS
cdr_begin                                                                   95
cdr_end                                                                    102
cdr_atoms                    [6701, 6702, 6703, 6704, 6705, 6706, 6707, 670...
epitope_atoms                [950, 2128, 2133, 2134, 2135, 2414, 2483, 2484...
epitope_residues             [105, 257, 257, 257, 257, 275, 280, 280, 280, ...
ag_ab_interface              {3584, 3592, 3593, 3596, 3597, 3599, 3600, 360...
ag_cdrchain_interface        {3584, 4738, 3582, 4742, 4358, 3592, 3593, 436...
ag_cdr_interface             {3584, 4738, 4742, 4358

In [448]:
pdb_filename = Path.joinpath(casa_dir, "tempo", buried_fullab.iloc[4805].idcode + ".pdb")
trj_in = md.load(pdb_filename)
serial_to_id = {}
for atomo in trj_in.topology.atoms:
    serial_to_id[atomo.serial] = atomo.index

ids_epitope_atoms = []
elementos_epitope_atoms = []
for id in buried_fullab.iloc[4805].epitope_atoms:
    elemento = trj_in.topology.atom(serial_to_id[id]).element.symbol
    if elemento != 'H':
        ids_epitope_atoms.append(serial_to_id[id])
        elementos_epitope_atoms.append(elemento)
ids_cdr_atoms = []
elementos_cdr_atoms = []
for id in buried_fullab.iloc[4805].cdr_atoms:
    elemento = trj_in.topology.atom(serial_to_id[id]).element.symbol
    if elemento != 'H':
        ids_cdr_atoms.append(serial_to_id[id])
        elementos_cdr_atoms.append(elemento)

ids_all_pairs = np.array(list(itertools.product(ids_cdr_atoms, ids_epitope_atoms)))
elementos_all_pairs = np.array(list(itertools.product(elementos_cdr_atoms,
    elementos_epitope_atoms)))

distancias = md.compute_distances(trj_in, ids_all_pairs).reshape((len(ids_cdr_atoms), len(ids_epitope_atoms)))

In [419]:
cutoff = 0.4
cc_indices = np.array([ i for i, (epi, cdr) in enumerate(elementos_all_pairs) if (epi == 'C' and cdr == 'C') ])

mask_contacto = distancias[0][cc_indices] < cutoff
distancias[0][cc_indices][mask_contacto]        

array([0.39248687, 0.37735313, 0.38968605, 0.3754475 , 0.38218588,
       0.35952342, 0.3839783 , 0.3733516 , 0.38643512, 0.35887206,
       0.38658956, 0.33757603, 0.3927317 , 0.39385   , 0.36813802,
       0.37953225, 0.387109  , 0.37213486, 0.36197805, 0.33804545,
       0.35399514, 0.38675603, 0.39775527, 0.36955428, 0.3806687 ,
       0.39368492, 0.35291353, 0.3768543 , 0.3686144 , 0.37549788,
       0.37686017, 0.36656833, 0.36433494], dtype=float32)

In [371]:
for x, y in ids_all_pairs[cc_indices[masc]]:
    print(f'cmd.show("spheres", "id ' + str(trj_in.topology.atom(x).serial) + f'")')
    print(f'cmd.show("spheres", "id ' + str(trj_in.topology.atom(y).serial) + f'")')

cmd.show("spheres", "id 6753")
cmd.show("spheres", "id 2497")
cmd.show("spheres", "id 6753")
cmd.show("spheres", "id 2500")
cmd.show("spheres", "id 6773")
cmd.show("spheres", "id 2497")
cmd.show("spheres", "id 6773")
cmd.show("spheres", "id 2498")
cmd.show("spheres", "id 6773")
cmd.show("spheres", "id 2500")
cmd.show("spheres", "id 6774")
cmd.show("spheres", "id 2497")
cmd.show("spheres", "id 6774")
cmd.show("spheres", "id 2498")
cmd.show("spheres", "id 6776")
cmd.show("spheres", "id 2497")
cmd.show("spheres", "id 6776")
cmd.show("spheres", "id 2498")
cmd.show("spheres", "id 6776")
cmd.show("spheres", "id 4653")
cmd.show("spheres", "id 6776")
cmd.show("spheres", "id 4655")
cmd.show("spheres", "id 6777")
cmd.show("spheres", "id 2497")
cmd.show("spheres", "id 6777")
cmd.show("spheres", "id 4653")
cmd.show("spheres", "id 6777")
cmd.show("spheres", "id 4655")
cmd.show("spheres", "id 6779")
cmd.show("spheres", "id 2484")
cmd.show("spheres", "id 6779")
cmd.show("spheres", "id 2487")
cmd.show

In [374]:
masc = distancias[0] < cutoff
masc

array([False, False, False, ..., False, False, False])

In [390]:
distancias[0][cc_indices][masc]

array([0.39248687, 0.37735313, 0.38968605, 0.3754475 , 0.38218588,
       0.35952342, 0.3839783 , 0.3733516 , 0.38643512, 0.35887206,
       0.38658956, 0.33757603, 0.3927317 , 0.39385   , 0.36813802,
       0.37953225, 0.387109  , 0.37213486, 0.36197805, 0.33804545,
       0.35399514, 0.38675603, 0.39775527, 0.36955428, 0.3806687 ,
       0.39368492, 0.35291353, 0.3768543 , 0.3686144 , 0.37549788,
       0.37686017, 0.36656833, 0.36433494], dtype=float32)

In [389]:
elementos_all_pairs[cc_indices][masc]

array([['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C']], dtype='<U1')

In [406]:
ids_all_pairs[cc_indices][masc][0:10]

array([[6764, 4652],
       [6766, 4652],
       [6783, 2511],
       [6794, 4887],
       [6801, 4877],
       [6801, 4878],
       [6811, 4884],
       [6811, 4887],
       [6821, 4278],
       [6822, 4278]])

In [399]:
cc_indices[np.where(masc)] == cc_indices[masc]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [442]:
a = distancias.reshape((len(ids_cdr_atoms), len(ids_epitope_atoms)))

In [460]:
sum((distancias < cutoff)[50, :])

2

In [472]:
np.apply_along_axis(lambda x: print(np.where(x < cutoff)), axis = 1, arr = distancias)

(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([ 9, 12]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([11]),)
(arr

array([None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, No

In [471]:
np.where(distancias[50, :] < cutoff)

(array([11, 23]),)

In [454]:
elementos_cdr_atoms

['N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'N',
 'C',
 'C',
 'O',
 'C',
 'O',
 'C',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'N',
 'C',
 'C',
 'N',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'O',
 'O',
 'N',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'N',
 'C',
 'N',
 'N',
 'N',
 'C',
 'C',
 'O',
 'C',
 'N',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'O',
 'N',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'O',
 'O',
 'N',
 'C'

In [445]:
a[0, :]

array([2.0432978, 1.9861699, 1.8967518, 1.7675161, 1.7450075, 1.8973789,
       1.7724223, 1.7072827, 1.6933233, 1.5735302, 1.6184837, 1.5498374,
       1.4964718, 1.7436111, 1.8082712, 1.8674103, 1.8940282, 1.815763 ,
       1.8056486, 1.7375678, 1.8614877, 1.9240737, 1.898266 , 1.7621412,
       1.9415541, 1.81661  , 1.8086228, 1.7376409, 1.767165 , 1.7528114,
       1.6175566, 1.6570061, 1.5980407, 1.5017939, 1.4761211, 1.4629812,
       1.3859426, 1.465231 , 1.5618888, 1.437118 , 1.5287368, 1.6672165,
       1.686091 , 1.4903144, 1.3741217, 1.3565539, 1.3136454, 1.9362253,
       1.8841699, 1.951203 , 1.9008027, 1.793962 , 1.9764191, 1.8239864,
       1.6744343, 1.5642012, 1.6518394, 1.5424112, 2.2270265, 2.2814355,
       1.9755428, 1.8588523, 1.8894477, 1.9248799, 1.7337414, 1.7110059,
       1.7018033, 1.8892237, 1.951364 , 1.8684572, 1.7560893, 1.9335456,
       1.8826832, 1.8626165, 1.7952182, 1.9880223, 2.124367 , 2.2282302,
       1.9329923, 1.9370219, 1.8112104, 1.800142 , 

In [446]:
ids_cdr_atoms

[6688,
 6689,
 6690,
 6691,
 6692,
 6693,
 6694,
 6704,
 6705,
 6706,
 6707,
 6708,
 6709,
 6710,
 6718,
 6719,
 6720,
 6721,
 6722,
 6723,
 6724,
 6725,
 6726,
 6727,
 6728,
 6738,
 6739,
 6740,
 6741,
 6742,
 6743,
 6744,
 6745,
 6746,
 6747,
 6748,
 6749,
 6759,
 6760,
 6761,
 6762,
 6763,
 6764,
 6765,
 6766,
 6767,
 6768,
 6777,
 6778,
 6779,
 6780,
 6781,
 6782,
 6783,
 6784,
 6785,
 6792,
 6793,
 6794,
 6795,
 6799,
 6800,
 6801,
 6802,
 6803,
 6804,
 6810,
 6811,
 6812,
 6813,
 6817,
 6818,
 6819,
 6820,
 6821,
 6822,
 6823,
 6824,
 6825,
 6826,
 6827,
 6828,
 6838,
 6839,
 6840,
 6841,
 6842,
 6843,
 6844,
 6845,
 6846,
 6847,
 6848,
 6849,
 6859,
 6860,
 6861,
 6862,
 6863,
 6864,
 6865,
 6866,
 6867,
 6868,
 6869,
 6870,
 6880,
 6881,
 6882,
 6883,
 6884,
 6885,
 6886,
 6887,
 6888,
 6889,
 6890,
 6904,
 6905,
 6906,
 6907,
 6908,
 6914,
 6915,
 6916,
 6917,
 6921,
 6922,
 6923,
 6924,
 6925,
 6926,
 6927,
 6928,
 6935,
 6936,
 6937,
 6938,
 6939,
 6940,
 6941,
 6942,
 6943,

In [431]:
# for carbono in cc_indices[masc]:

carbono_cdr = ids_all_pairs[cc_indices[mask_contacto]][0][0]
[ y for x, y in ids_all_pairs if x == carbono_cdr]

[2127,
 2413,
 2482,
 2483,
 2484,
 2485,
 2486,
 2488,
 2495,
 2496,
 2497,
 2498,
 2499,
 2505,
 2506,
 2507,
 2510,
 2511,
 2512,
 2513,
 2527,
 2528,
 2531,
 2532,
 2533,
 3503,
 3504,
 3505,
 3506,
 3507,
 3508,
 3514,
 3515,
 3516,
 3517,
 3521,
 3522,
 3523,
 3524,
 3528,
 3529,
 3530,
 3531,
 3532,
 3533,
 3534,
 3535,
 3560,
 3563,
 3564,
 3565,
 3566,
 3567,
 3574,
 3578,
 3579,
 3580,
 3581,
 3649,
 3651,
 4205,
 4206,
 4207,
 4208,
 4209,
 4210,
 4212,
 4219,
 4220,
 4221,
 4222,
 4236,
 4237,
 4238,
 4239,
 4240,
 4241,
 4242,
 4260,
 4261,
 4262,
 4263,
 4277,
 4278,
 4279,
 4280,
 4649,
 4650,
 4652,
 4653,
 4654,
 4662,
 4663,
 4664,
 4665,
 4686,
 4687,
 4688,
 4689,
 4690,
 4693,
 4698,
 4828,
 4830,
 4850,
 4851,
 4862,
 4863,
 4869,
 4870,
 4871,
 4872,
 4876,
 4877,
 4878,
 4879,
 4883,
 4884,
 4885,
 4886,
 4887,
 4888,
 4889,
 4890,
 4898,
 4900,
 4939,
 4941]

In [416]:
# Find starting y end index de 6764
# tomar la máscara de todas sus distancias que sean menores que el cutoff
# Fijarse en los IDs del elemento [1] de esos pares q sean O o N y también los q sean C (p/ inclurlos)

# Fijar criterios!

ids_all_pairs[5370:5380]

array([[6763, 4889],
       [6763, 4890],
       [6763, 4898],
       [6763, 4900],
       [6763, 4939],
       [6763, 4941],
       [6764, 2127],
       [6764, 2413],
       [6764, 2482],
       [6764, 2483]])

In [550]:
# Collect all contacts of the CDR carbons, in a dict of dicts. 
# Keys of the outer dict are the IDs of each CDR carbon.
# The corresponding values are also dicts, with 3 keys each, 
# the element of the interacting epitope atom: O, N and S
# The corresponding values are numpy arrays of tuples. Each tuple corresponds
# to an interacting epitope atom. The first element is the ID of the epitope atom
# and the second element is its distance from the corresponding CDR atom.
# So, cdr_C_contacts[6761]['C'] is a numpy array of tuples with all the epitope atoms that
# are interacting with the CDR carbon with an ID of 6761 and that are also carbons themselves.
cdr_C_contacts = {}
for i, j in zip(*np.where(distancias < cutoff)):
    if elementos_cdr_atoms[i] == 'C':
        cdr_atom_id = ids_cdr_atoms[i]
        epitope_atom_id = ids_epitope_atoms[j]
        epitope_atom_element = elementos_epitope_atoms[j]

        if cdr_atom_id not in cdr_C_contacts:
            cdr_C_contacts[cdr_atom_id] = {}

        if epitope_atom_element in cdr_C_contacts[cdr_atom_id]:
            cdr_C_contacts[cdr_atom_id][epitope_atom_element].append(
                (epitope_atom_id, distancias[i, j]))
        else:
            cdr_C_contacts[cdr_atom_id][epitope_atom_element] = [(epitope_atom_id, distancias[i, j])]

In [557]:
cdr_C_contacts[6764]

{'C': [(4652, 0.39248687)]}

In [564]:
trj_in.xyz[0][6764, :]

array([-3.3322,  2.8615,  0.7918], dtype=float32)

In [558]:
(al[6764], al[4652])

(HIS99-CG, THR455-CB)

In [559]:
(al[6764].serial, al[4652].serial)

(6777, 4653)

In [383]:
masc = distancias[0][cc_indices] < cutoff

In [151]:
a = next(trj_in.topology.atoms)

In [208]:
trj_in.topology.atoms

<generator object Topology.atoms at 0x7fc481e07c10>

In [68]:
buried_fullab.query(f"idcode == '4ydk'").


idcode chainID chain_type  cdr               cdr_seq  cdr_begin  \
10761   4ydk       H          H    1               GFTFNNY         26   
10762   4ydk       H          H    2                SAHGGS         52   
10763   4ydk       H          H    3  VTFYHEGSGYYYRAGNYFDS         95   
10764   4ydk       L          K    1           RASQDIANYLN         24   
10765   4ydk       L          K    2               GATNLHH         50   
10766   4ydk       L          K    3             QQSFQTVGS         89   

       cdr_end                                          cdr_atoms  \
10761       32  [5552, 5553, 5554, 5555, 5556, 5557, 5558, 555...   
10762       56  [5963, 5964, 5965, 5966, 5967, 5968, 5969, 597...   
10763      102  [6701, 6702, 6703, 6704, 6705, 6706, 6707, 670...   
10764       34  [8957, 8958, 8959, 8960, 8961, 8962, 8963, 896...   
10765       56  [9393, 9394, 9395, 9396, 9397, 9398, 9399, 940...   
10766       97  [9962, 9963, 9964, 9965, 9966, 9967, 9968, 996...   

                                           epitope_atoms  \
10761                                                 []   
10762  [1209, 1233, 1238, 1243, 1244, 3530, 3533, 353...   
10763  [950, 2128, 2133, 2134, 2135, 2414, 2483, 2484...   
10764  [2489, 2494, 2495, 3508, 3509, 3510, 3512, 351...   
10765  [2488, 2494, 4708, 4711, 4713, 4714, 4715, 471...   
10766  [3504, 3505, 3506, 3507, 3508, 3509, 3510, 351...   

                                        epitope_residues  \
10761                                                 []   
10762  [122, 123, 123, 124, 124, 368, 368, 368, 368, ...   
10763  [105, 257, 257, 257, 257, 275, 280, 280, 280, ...   
10764  [280, 280, 280, 365, 365, 365, 365, 365, 365, ...   
10765  [280, 280, 459, 459, 460, 460, 460, 460, 460, ...   
10766  [365, 365, 365, 365, 365, 365, 365, 365, 365, ...   

                                         ag_ab_interface  \
10761  {3584, 3592, 3593, 3596, 3597, 3599, 3600, 360...   
10762  {3584, 3592, 3593, 3596, 3597, 3599, 3600, 360...   
10763  {3584, 3592, 3593, 3596, 3597, 3599, 3600, 360...   
10764  {3584, 3592, 3593, 3596, 3597, 3599, 3600, 360...   
10765  {3584, 3592, 3593, 3596, 3597, 3599, 3600, 360...   
10766  {3584, 3592, 3593, 3596, 3597, 3599, 3600, 360...   

                                   ag_cdrchain_interface  \
10761  {3584, 4738, 3582, 4742, 4358, 3592, 3593, 436...   
10762  {3584, 4738, 3582, 4742, 4358, 3592, 3593, 436...   
10763  {3584, 4738, 3582, 4742, 4358, 3592, 3593, 436...   
10764  {3523, 3524, 4772, 4771, 4778, 4781, 4912, 491...   
10765  {3523, 3524, 4772, 4771, 4778, 4781, 4912, 491...   
10766  {3523, 3524, 4772, 4771, 4778, 4781, 4912, 491...   

                                        ag_cdr_interface  \
10761                                                 {}   
10762               {4397, 4378, 4379, 4380, 4381, 4383}   
10763  {3584, 4738, 4742, 4358, 3592, 3593, 4745, 474...   
10764                           {4912, 4913, 4772, 4781}   
10765                                                 {}   
10766                                 {3523, 3524, 3519}   

                                         ab_ag_interface  \
10761  {6323, 6338, 6851, 6853, 6855, 6857, 6859, 686...   
10762  {6323, 6338, 6851, 6853, 6855, 6857, 6859, 686...   
10763  {6323, 6338, 6851, 6853, 6855, 6857, 6859, 686...   
10764  {6323, 6338, 6851, 6853, 6855, 6857, 6859, 686...   
10765  {6323, 6338, 6851, 6853, 6855, 6857, 6859, 686...   
10766  {6323, 6338, 6851, 6853, 6855, 6857, 6859, 686...   

                                     ag_ab_interface_res  \
10761  [(G, 370, GLU, HG2, 1), (G, 371, ILE, CG2, 1),...   
10762  [(G, 370, GLU, HG2, 2), (G, 371, ILE, CG2, 2),...   
10763  [(G, 370, GLU, HG2, 3), (G, 371, ILE, CG2, 3),...   
10764  [(G, 370, GLU, HG2, 1), (G, 371, ILE, CG2, 1),...   
10765  [(G, 370, GLU, HG2, 2), (G, 371, ILE, CG2, 2),...   
10766  [(G, 370, GLU, HG2, 3), (G, 371, ILE, CG2, 3),...   

                               ag_cdrchain_interface_res  \
107